# BTCC PDF Scraper


The python tabula wrapper doesnlt appear to work... so let's try the R one...

In [1]:
install.packages("tabulizer")

also installing the dependencies ‘png’, ‘rJava’, ‘tabulizerjars’




The downloaded binary packages are in
	/var/folders/l8/qg6m44156_l6bzv_cbkk7bf00000gn/T//RtmplMg8At/downloaded_packages


In [2]:
#sudo R CMD javareconf
library("tabulizer")
out1 <- extract_tables("2019/191403cli.pdf")

In [3]:
out1

[[1]]
     [,1]                 [,2]                                                
[1,] ""                   "Length 1.2079 miles"                               
[2,] ""                   "FL"                                                
[3,] ""                   "I1 1112m"                                          
[4,] ""                   "Pit Entry 1669m"                                   
[5,] ""                   "Pit Exit 0m after FL"                              
[6,] ""                   "Pit Entry–Pit Exit 251m, 15.0s @60kph, 11.3s @80kp"
[7,] "www.tsl-timing.com" ""                                                  
     [,3]         [,4]       
[1,] "1944.0 m"   ""         
[2,] "51.36032 N" "0.26032 E"
[3,] "51.35934 N" "0.25955 E"
[4,] "51.35911 N" "0.25743 E"
[5,] "51.36017 N" "0.26051 E"
[6,] ""           ""         
[7,] ""           ""         

[[2]]
      [,1]  [,2]   [,3] [,4]  [,5]              [,6] 
 [1,] "POS" "NO"   "CL" "PIC" "NAME"            "NAT"
 [2,] "1"   "71"   ""   "1"   "Max COATES"      "GBR"
 [3,] "2"   "62"   "G"  "1"   "Jack YOUNG"      "GBR"
 [4,] "3"   "23 *" "G"  "2"   "Ethan HAMMERTON" "GBR"
 [5,] "4"   "12"   ""   "2"   "Brett LIDSEY"    "GBR"
 [6,] "5"   "21 *" ""   "3"   "Ben DAVIS"       "GBR"
 [7,] "6"   "5"    "G"  "3"   "Ben COLBURN"     "GBR"
 [8,] "7"   "41 *" ""   "4"   "Aaron THOMPSON"  "GBR"
 [9,] "8"   "14 *" ""   "5"   "Anton SPIRES"    "GBR"
[10,] "9"   "9 *"  ""   "6"   "Jade EDWARDS"    "GBR"
[11,] "10"  "29"   "G"  "4"   "Finlay ROBINSON" "GBR"
[12,] "11"  "11"   ""   "7"   "Luke WARR"       "GBR"
      [,7]                        [,8]     [,9] [,10]  [,11]   [,12]   [,13]  
 [1,] "ENTRY"                     "TIME"   "ON" "LAPS" "GAP"   "DIFF"  "MPH"  
 [2,] "Team Hard"                 "52.366" "23" "29"   ""      ""      "83.04"
 [3,] "M.R.M"                     "52.409" "20" "25"   "0.043" "0.043" "82.97"
 [4,] "Team Hard"                 "52.466" "20" "28"   "0.100" "0.057" "82.88"
 [5,] "M.R.M"                     "52.499" "22" "24"   "0.133" "0.033" "82.83"
 [6,] "R-Tech Welding with M.R.M" "52.580" "20" "25"   "0.214" "0.081" "82.70"
 [7,] "Westbourne Motorsport"     "52.607" "20" "30"   "0.241" "0.027" "82.66"
 [8,] "Westbourne Motorsport"     "52.754" "20" "29"   "0.388" "0.147" "82.43"
 [9,] "Westbourne Motorsport"     "52.877" "26" "29"   "0.511" "0.123" "82.23"
[10,] "Team Hard"                 "52.900" "23" "28"   "0.534" "0.023" "82.20"
[11,] "Westbourne Motorsport"     "53.090" "22" "23"   "0.724" "0.190" "81.91"
[12,] "Specialized Motorsport"    "54.489" "22" "28"   "2.123" "1.399" "79.80"

[[3]]
      [,1]  [,2]   [,3] [,4]  [,5]              [,6] 
 [1,] "POS" "NO"   "CL" "PIC" "NAME"            "NAT"
 [2,] "1"   "71"   ""   "1"   "Max COATES"      "GBR"
 [3,] "2"   "62"   "G"  "1"   "Jack YOUNG"      "GBR"
 [4,] "3"   "12"   ""   "2"   "Brett LIDSEY"    "GBR"
 [5,] "4"   "23 *" "G"  "2"   "Ethan HAMMERTON" "GBR"
 [6,] "5"   "21 *" ""   "3"   "Ben DAVIS"       "GBR"
 [7,] "6"   "5"    "G"  "3"   "Ben COLBURN"     "GBR"
 [8,] "7"   "41 *" ""   "4"   "Aaron THOMPSON"  "GBR"
 [9,] "8"   "14 *" ""   "5"   "Anton SPIRES"    "GBR"
[10,] "9"   "9 *"  ""   "6"   "Jade EDWARDS"    "GBR"
[11,] "10"  "29"   "G"  "4"   "Finlay ROBINSON" "GBR"
[12,] "11"  "11"   ""   "7"   "Luke WARR"       "GBR"
      [,7]                        [,8]     [,9] [,10]  [,11]   [,12]   [,13]  
 [1,] "ENTRY"                     "TIME"   "ON" "LAPS" "GAP"   "DIFF"  "MPH"  
 [2,] "Team Hard"                 "52.433" "28" "29"   ""      ""      "82.93"
 [3,] "M.R.M"                     "52.439" "17" "25"   "0.006" "0.006" "82.92"
 [4,] "M.R.M"                     "52.566" "24" "24"   "0.133" "0.127" "82.72"
 [5,] "Team Hard"                 "52.617" "23" "28"   "0.184" "0.051" "82.64"
 [6,] "R-Tech Welding with M.R.M" "52.640" "21" "25"   "0.207" "0.023" "82.61"
 [7,] "Westbourne Motorsport"     "52.696" "24" "30"   "0.263" "0.056" "82.52"
 [8,] "Westbourne Motorsport"     "52.768" "1

In [ ]:
#Need to  doc to get info about what's on each page

In [7]:
extract_tables("2019/191403cli.pdf", pages = 2)

[[1]]
     [,1]                 [,2]                                                
[1,] ""                   "Length 1.2079 miles"                               
[2,] ""                   "FL"                                                
[3,] ""                   "I1 1112m"                                          
[4,] ""                   "Pit Entry 1669m"                                   
[5,] ""                   "Pit Exit 0m after FL"                              
[6,] ""                   "Pit Entry–Pit Exit 251m, 15.0s @60kph, 11.3s @80kp"
[7,] "www.tsl-timing.com" ""                                                  
     [,3]         [,4]       
[1,] "1944.0 m"   ""         
[2,] "51.36032 N" "0.26032 E"
[3,] "51.35934 N" "0.25955 E"
[4,] "51.35911 N" "0.25743 E"
[5,] "51.36017 N" "0.26051 E"
[6,] ""           ""         
[7,] ""           ""

In [8]:
extract_tables("2019/191403cli.pdf", pages = 3)

[[1]]
      [,1]  [,2]   [,3] [,4]  [,5]              [,6] 
 [1,] "POS" "NO"   "CL" "PIC" "NAME"            "NAT"
 [2,] "1"   "71"   ""   "1"   "Max COATES"      "GBR"
 [3,] "2"   "62"   "G"  "1"   "Jack YOUNG"      "GBR"
 [4,] "3"   "23 *" "G"  "2"   "Ethan HAMMERTON" "GBR"
 [5,] "4"   "12"   ""   "2"   "Brett LIDSEY"    "GBR"
 [6,] "5"   "21 *" ""   "3"   "Ben DAVIS"       "GBR"
 [7,] "6"   "5"    "G"  "3"   "Ben COLBURN"     "GBR"
 [8,] "7"   "41 *" ""   "4"   "Aaron THOMPSON"  "GBR"
 [9,] "8"   "14 *" ""   "5"   "Anton SPIRES"    "GBR"
[10,] "9"   "9 *"  ""   "6"   "Jade EDWARDS"    "GBR"
[11,] "10"  "29"   "G"  "4"   "Finlay ROBINSON" "GBR"
[12,] "11"  "11"   ""   "7"   "Luke WARR"       "GBR"
      [,7]                        [,8]     [,9] [,10]  [,11]   [,12]   [,13]  
 [1,] "ENTRY"                     "TIME"   "ON" "LAPS" "GAP"   "DIFF"  "MPH"  
 [2,] "Team Hard"                 "52.366" "23" "29"   ""      ""      "83.04"
 [3,] "M.R.M"                     "52.409" "20" "25"   "0.043" "0.043" "82.97"
 [4,] "Team Hard"                 "52.466" "20" "28"   "0.100" "0.057" "82.88"
 [5,] "M.R.M"                     "52.499" "22" "24"   "0.133" "0.033" "82.83"
 [6,] "R-Tech Welding with M.R.M" "52.580" "20" "25"   "0.214" "0.081" "82.70"
 [7,] "Westbourne Motorsport"     "52.607" "20" "30"   "0.241" "0.027" "82.66"
 [8,] "Westbourne Motorsport"     "52.754" "20" "29"   "0.388" "0.147" "82.43"
 [9,] "Westbourne Motorsport"     "52.877" "26" "29"   "0.511" "0.123" "82.23"
[10,] "Team Hard"                 "52.900" "23" "28"   "0.534" "0.023" "82.20"
[11,] "Westbourne Motorsport"     "53.090" "22" "23"   "0.724" "0.190" "81.91"
[12,] "Specialized Motorsport"    "54.489" "22" "28"   "2.123" "1.399" "79.80"

In [17]:
extract_tables("2019/191403cli.pdf", pages = 4)

[[1]]
      [,1]  [,2]   [,3] [,4]  [,5]              [,6] 
 [1,] "POS" "NO"   "CL" "PIC" "NAME"            "NAT"
 [2,] "1"   "71"   ""   "1"   "Max COATES"      "GBR"
 [3,] "2"   "62"   "G"  "1"   "Jack YOUNG"      "GBR"
 [4,] "3"   "12"   ""   "2"   "Brett LIDSEY"    "GBR"
 [5,] "4"   "23 *" "G"  "2"   "Ethan HAMMERTON" "GBR"
 [6,] "5"   "21 *" ""   "3"   "Ben DAVIS"       "GBR"
 [7,] "6"   "5"    "G"  "3"   "Ben COLBURN"     "GBR"
 [8,] "7"   "41 *" ""   "4"   "Aaron THOMPSON"  "GBR"
 [9,] "8"   "14 *" ""   "5"   "Anton SPIRES"    "GBR"
[10,] "9"   "9 *"  ""   "6"   "Jade EDWARDS"    "GBR"
[11,] "10"  "29"   "G"  "4"   "Finlay ROBINSON" "GBR"
[12,] "11"  "11"   ""   "7"   "Luke WARR"       "GBR"
      [,7]                        [,8]     [,9] [,10]  [,11]   [,12]   [,13]  
 [1,] "ENTRY"                     "TIME"   "ON" "LAPS" "GAP"   "DIFF"  "MPH"  
 [2,] "Team Hard"                 "52.433" "28" "29"   ""      ""      "82.93"
 [3,] "M.R.M"                     "52.439" "17" "25"   "0.006" "0.006" "82.92"
 [4,] "M.R.M"                     "52.566" "24" "24"   "0.133" "0.127" "82.72"
 [5,] "Team Hard"                 "52.617" "23" "28"   "0.184" "0.051" "82.64"
 [6,] "R-Tech Welding with M.R.M" "52.640" "21" "25"   "0.207" "0.023" "82.61"
 [7,] "Westbourne Motorsport"     "52.696" "24" "30"   "0.263" "0.056" "82.52"
 [8,] "Westbourne Motorsport"     "52.768" "19" "29"   "0.335" "0.072" "82.40"
 [9,] "Westbourne Motorsport"     "52.920" "27" "29"   "0.487" "0.152" "82.17"
[10,] "Team Hard"                 "53.020" "25" "28"   "0.587" "0.100" "82.01"
[11,] "Westbourne Motorsport"     "53.258" "21" "23"   "0.825" "0.238" "81.65"
[12,] "Specialized Motorsport"    "54.527" "21" "28"   "2.094" "1.269" "79.75"

In [19]:
#this sort of thing will need cleaning...
extract_tables("2019/191403cli.pdf", pages = 5:10)

[[1]]
      [,1]                                                                             
 [1,] "SECTOR 1 = FL to I1,SECTOR 2 = I1 to FL,DIFF = Difference To Personal Best Lap,"
 [2,] "P1 71 Max COATES"                                                               
 [3,] "IDEAL LAP TIME :  52.351 BEST LAP TIME :  52.366"                               
 [4,] "LAP SECTOR 1 SECTOR 2"                                                          
 [5,] "1 - OUTLAP 72.9 26.688 92.0"                                                    
 [6,] "2 - 37.998 80.4 23.562 106.3"                                                   
 [7,] "3 - 33.645 89.0 22.133 109.6"                                                   
 [8,] "4 - 32.365 92.4 22.059 109.8"                                                   
 [9,] "5 - 32.082 92.5 21.828 110.1"                                                   
[10,] "6 - 31.926 93.4 21.799 110.3"                                                   
[11,] "7 - 32.026 92.4 21.909 110.3"                                                   
[12,] "8 - 31.657 93.8 21.558 110.7"                                                   
[13,] "9 - 31.776 92.5 21.837 110.7"                                                   
[14,] "10 - 31.840 93.8 22.216 109.8"                                                  
[15,] "11 - 31.805 94.1 21.935 109.4"                                                  
[16,] "12 - 31.639 94.2 21.514 109.4"                                                  
[17,] "13 - 31.348 93.8 21.537 109.8"                                                  
[18,] "14 - 31.406 94.7 22.317 108.9"                                                  
[19,] "15 - 33.054 90.6 IN PIT"                                                        
[20,] "16 - OUTLAP 72.4 24.610 101.5"                                                  
[21,] "17 - 35.261 87.1 23.505 107.3"                                                  
[22,] "18 - 34.237 76.6 22.944 106.8"                                                  
[23,] "19 - 32.745 82.9 22.087 109.8"                                                  
[24,] "20 - 32.644 73.8 22.056 109.8"                                                  
[25,] "21 - 31.384 94.1 21.313 109.6"                                                  
[26,] "22 - 31.175 94.3 21.336 110.0"                                                  
[27,] "23 - 31.153 94.6 21.213 110.5"                                                  
[28,] "24 - 31.204 94.7 21.232 110.7"                                                  
[29,] "25 - 31.148 95.3 21.293 110.9"                                                  
[30,] "26 - 31.280 94.9 21.316 110.1"                                                  
[31,] "27 - 31.249 94.9 21.355 109.4"                                                  
[32,] "28 - 31.138 95.1 21.295 110.3"                                                  
[33,] "29 - 31.320 94.2 21.483 110.3"                                                  
[34,] "P2 62 G Jack YOUNG"                                                             
[35,] "IDEAL LAP TIME :  52.384 BEST LAP TIME :  52.409"                               
[36,] "LAP SECTOR 1 SECTOR 2"                                                          
[37,] "1 - OUTLAP 77.6 23.589 106.0"                                                   
[38,] "2 - 35.380 85.9 22.622 107.3"                                                   
[39,] "3 - 33.760 89.3 22.080 107.8"                                                   
[40,] "4 - 33.001 87.9 21.932 110.0"                                                   
[41,] "5 - 32.121 92.9 21.669 110.0"                                                   
[42,] "6 - 32.152 93.2 21.705 110.0"                                                   
[43,] "7 - 31.944 93.3 21.662 110.3"                                                   
[44,] "8 - 31.800 93.4 21.436 110.7"                                                   
[45,] "9 - 31.485 94.1 21.485 110.

In [11]:
extract_tables("2019/191403cli.pdf", pages = 11)

[[1]]
      [,1] [,2] [,3]        [,4]   [,5] [,6]        [,7]   
 [1,] "1"  "21" "DAVIS"     "95.8" "21" "DAVIS"     "113.9"
 [2,] "2"  "12" "LIDSEY"    "95.7" "41" "THOMPSON"  "112.7"
 [3,] "3"  "71" "COATES"    "95.3" "62" "YOUNG"     "112.5"
 [4,] "4"  "62" "YOUNG"     "95.3" "23" "HAMMERTON" "112.5"
 [5,] "5"  "41" "THOMPSON"  "95.3" "12" "LIDSEY"    "112.4"
 [6,] "6"  "9"  "EDWARDS"   "95.1" "14" "SPIRES"    "112.2"
 [7,] "7"  "23" "HAMMERTON" "95.0" "9"  "EDWARDS"   "112.2"
 [8,] "8"  "5"  "COLBURN"   "95.0" "5"  "COLBURN"   "111.8"
 [9,] "9"  "14" "SPIRES"    "94.6" "71" "COATES"    "110.9"
[10,] "10" "29" "ROBINSON"  "94.1" "29" "ROBINSON"  "110.7"
[11,] "11" "11" "WARR"      "93.4" "11" "WARR"      "110.0"

In [12]:
extract_tables("2019/191403cli.pdf", pages = 12)

[[1]]
      [,1] [,2] [,3]        [,4]     [,5] [,6]        [,7]     [,8] [,9]
 [1,] ""   ""   ""          ""       ""   ""          ""       ""   ""  
 [2,] "1"  "71" "COATES"    "31.138" "62" "YOUNG"     "21.186" "1"  "71"
 [3,] "2"  "23" "HAMMERTON" "31.174" "12" "LIDSEY"    "21.206" "2"  "62"
 [4,] "3"  "62" "YOUNG"     "31.198" "71" "COATES"    "21.213" "3"  "12"
 [5,] "4"  "12" "LIDSEY"    "31.223" "21" "DAVIS"     "21.266" "4"  "23"
 [6,] "5"  "21" "DAVIS"     "31.262" "5"  "COLBURN"   "21.282" "5"  "21"
 [7,] "6"  "41" "THOMPSON"  "31.274" "23" "HAMMERTON" "21.292" "6"  "5" 
 [8,] "7"  "5"  "COLBURN"   "31.325" "9"  "EDWARDS"   "21.322" "7"  "41"
 [9,] "8"  "14" "SPIRES"    "31.337" "29" "ROBINSON"  "21.366" "8"  "14"
[10,] "9"  "9"  "EDWARDS"   "31.531" "41" "THOMPSON"  "21.369" "9"  "9" 
[11,] "10" "29" "ROBINSON"  "31.710" "14" "SPIRES"    "21.420" "10" "29"
[12,] "11" "11" "WARR"      "32.554" "11" "WARR"      "21.804" "11" "11"
      [,10]         [,11]    [,12]    [,13]  
 [1,] "PERFECT LAP" "52.324" ""       ""     
 [2,] "COATES"      "52.351" "52.366" "0.015"
 [3,] "YOUNG"       "52.384" "52.409" "0.025"
 [4,] "LIDSEY"      "52.429" "52.499" "0.070"
 [5,] "HAMMERTON"   "52.466" "52.466" "0.000"
 [6,] "DAVIS"       "52.528" "52.580" "0.052"
 [7,] "COLBURN"     "52.607" "52.607" "0.000"
 [8,] "THOMPSON"    "52.643" "52.754" "0.111"
 [9,] "SPIRES"      "52.757" "52.877" "0.120"
[10,] "EDWARDS"     "52.853" "52.900" "0.047"
[11,] "ROBINSON"    "53.076" "53.090" "0.014"
[12,] "WARR"        "54.358" "54.489" "0.131"

In [18]:
extract_tables("2019/191403cli.pdf", pages = 14)

[[1]]
      [,1] [,2] [,3]              [,4]       [,5]           [,6]  [,7]       
 [1,] "NO" "CL" "NAME"            "LAP TIME" "TIME OF DAY"  "LAP" "VEHICLE"  
 [2,] "62" "G"  "Jack YOUNG"      "58.002"   "11:26:12.149" "2"   "M.R.M"    
 [3,] "62" "G"  "Jack YOUNG"      "55.840"   "11:27:07.990" "3"   "M.R.M"    
 [4,] "71" ""   "Max COATES"      "55.778"   "11:27:18.963" "3"   "Team Hard"
 [5,] "23" "G"  "Ethan HAMMERTON" "55.358"   "11:27:19.258" "3"   "Team Hard"
 [6,] "62" "G"  "Jack YOUNG"      "54.933"   "11:28:02.921" "4"   "M.R.M"    
 [7,] "71" ""   "Max COATES"      "54.424"   "11:28:13.386" "4"   "Team Hard"
 [8,] "62" "G"  "Jack YOUNG"      "53.790"   "11:28:56.712" "5"   "M.R.M"    
 [9,] "71" ""   "Max COATES"      "53.725"   "11:30:01.022" "6"   "Team Hard"
[10,] "62" "G"  "Jack YOUNG"      "53.606"   "11:30:44.174" "7"   "M.R.M"    
[11,] "62" "G"  "Jack YOUNG"      "53.236"   "11:31:37.409" "8"   "M.R.M"    
[12,] "71" ""   "Max COATES"      "53.215"   "11:31:48.171" "8"   "Team Hard"
[13,] "62" "G"  "Jack YOUNG"      "52.970"   "11:32:30.381" "9"   "M.R.M"    
[14,] "71" ""   "Max COATES"      "52.885"   "11:36:15.619" "13"  "Team Hard"
[15,] "62" "G"  "Jack YOUNG"      "52.697"   "11:43:35.421" "14"  "M.R.M"    
[16,] "62" "G"  "Jack YOUNG"      "52.501"   "11:45:21.890" "16"  "M.R.M"    
[17,] "62" "G"  "Jack YOUNG"      "52.439"   "11:46:14.330" "17"  "M.R.M"    
[18,] "71" ""   "Max COATES"      "52.366"   "11:48:41.567" "23"  "Team Hard"

[[2]]
     [,1]     [,2]           [,3]         [,4]    [,5]         [,6]        
[1,] "TYPE"   "TIME OF DAY"  "TYPE"       "COUNT" "TOTAL LAPS" "TOTAL TIME"
[2,] "GREEN"  "11:24:00.984" "Green"      "1"     "29"         "30:00.923" 
[3,] "FINISH" "11:54:01.907" "Red"        "0"     "0"          "0.000"     
[4,] ""       ""             "Safety Car" "0"     "0"          "0.000"     
[5,] ""       ""             "FCY"        "0"     "0"          "0.000"

In [20]:
extract_tables("2019/191403cli.pdf", pages = 15)

[[1]]
      [,1] [,2]             [,3]       [,4]           [,5] 
 [1,] "NO" "NAME"           "LAP TIME" "TIME OF DAY"  "LAP"
 [2,] "21" "Ben DAVIS"      "59.738"   "11:26:14.775" "2"  
 [3,] "12" "Brett LIDSEY"   "59.559"   "11:26:26.047" "2"  
 [4,] "41" "Aaron THOMPSON" "59.335"   "11:26:26.624" "2"  
 [5,] "14" "Anton SPIRES"   "59.110"   "11:26:27.060" "2"  
 [6,] "21" "Ben DAVIS"      "56.989"   "11:27:11.762" "3"  
 [7,] "71" "Max COATES"     "55.778"   "11:27:18.963" "3"  
 [8,] "71" "Max COATES"     "54.424"   "11:28:13.386" "4"  
 [9,] "71" "Max COATES"     "53.910"   "11:29:07.296" "5"  
[10,] "71" "Max COATES"     "53.725"   "11:30:01.022" "6"  
[11,] "71" "Max COATES"     "53.215"   "11:31:48.171" "8"  
[12,] "71" "Max COATES"     "53.153"   "11:35:22.733" "12" 
[13,] "71" "Max COATES"     "52.885"   "11:36:15.619" "13" 
[14,] "41" "Aaron THOMPSON" "52.768"   "11:45:35.148" "19" 
[15,] "12" "Brett LIDSEY"   "52.686"   "11:46:09.171" "19" 
[16,] "71" "Max COATES"     "52.511"   "11:47:49.202" "22" 
[17,] "71" "Max COATES"     "52.366"   "11:48:41.567" "23" 
      [,6]                       
 [1,] "VEHICLE"                  
 [2,] "R-Tech Welding with M.R.M"
 [3,] "M.R.M"                    
 [4,] "Westbourne Motorsport"    
 [5,] "Westbourne Motorsport"    
 [6,] "R-Tech Welding with M.R.M"
 [7,] "Team Hard"                
 [8,] "Team Hard"                
 [9,] "Team Hard"                
[10,] "Team Hard"                
[11,] "Team Hard"                
[12,] "Team Hard"                
[13,] "Team Hard"                
[14,] "Westbourne Motorsport"    
[15,] "M.R.M"                    
[16,] "Team Hard"                
[17,] "Team Hard"

In [21]:
extract_tables("2019/191403cli.pdf", pages = 16)

[[1]]
      [,1] [,2]              [,3]       [,4]           [,5]  [,6]       
 [1,] "NO" "NAME"            "LAP TIME" "TIME OF DAY"  "LAP" "VEHICLE"  
 [2,] "62" "Jack YOUNG"      "58.002"   "11:26:12.149" "2"   "M.R.M"    
 [3,] "62" "Jack YOUNG"      "55.840"   "11:27:07.990" "3"   "M.R.M"    
 [4,] "23" "Ethan HAMMERTON" "55.358"   "11:27:19.258" "3"   "Team Hard"
 [5,] "62" "Jack YOUNG"      "54.933"   "11:28:02.921" "4"   "M.R.M"    
 [6,] "23" "Ethan HAMMERTON" "54.437"   "11:28:13.695" "4"   "Team Hard"
 [7,] "62" "Jack YOUNG"      "53.790"   "11:28:56.712" "5"   "M.R.M"    
 [8,] "62" "Jack YOUNG"      "53.606"   "11:30:44.174" "7"   "M.R.M"    
 [9,] "62" "Jack YOUNG"      "53.236"   "11:31:37.409" "8"   "M.R.M"    
[10,] "62" "Jack YOUNG"      "52.970"   "11:32:30.381" "9"   "M.R.M"    
[11,] "62" "Jack YOUNG"      "52.697"   "11:43:35.421" "14"  "M.R.M"    
[12,] "62" "Jack YOUNG"      "52.501"   "11:45:21.890" "16"  "M.R.M"    
[13,] "62" "Jack YOUNG"      "52.439"   "11:46:14.330" "17"  "M.R.M"    
[14,] "62" "Jack YOUNG"      "52.409"   "11:48:56.953" "20"  "M.R.M"

In [24]:
extract_tables("2019/191403cli.pdf", pages = 19)

[[1]]
      [,1]  [,2] [,3] [,4]  [,5]              [,6]  [,7]                       
 [1,] "POS" "NO" "CL" "PIC" "NAME"            "NAT" "ENTRY"                    
 [2,] "1"   "71" ""   "1"   "Max COATES"      "GBR" "Team Hard"                
 [3,] "2"   "62" "G"  "1"   "Jack YOUNG"      "GBR" "M.R.M"                    
 [4,] "3"   "12" ""   "2"   "Brett LIDSEY"    "GBR" "M.R.M"                    
 [5,] "4"   "23" "G"  "2"   "Ethan HAMMERTON" "GBR" "Team Hard"                
 [6,] "5"   "9"  ""   "3"   "Jade EDWARDS"    "GBR" "Team Hard"                
 [7,] "6"   "41" ""   "4"   "Aaron THOMPSON"  "GBR" "Westbourne Motorsport"    
 [8,] "7"   "29" "G"  "3"   "Finlay ROBINSON" "GBR" "Westbourne Motorsport"    
 [9,] "8"   "21" ""   "5"   "Ben DAVIS"       "GBR" "R-Tech Welding with M.R.M"
[10,] "9"   "5"  "G"  "4"   "Ben COLBURN"     "GBR" "Westbourne Motorsport"    
[11,] "10"  "11" ""   "6"   "Luke WARR"       "GBR" "Specialized Motorsport"   
[12,] ""    ""   ""   ""    ""                ""    "NOT CLASSIFIED"           
[13,] "DNF" "14" ""   ""    "Anton SPIRES"    "GBR" "Westbourne Motorsport"    
[14,] ""    ""   ""   ""    ""                ""    "FASTEST LAP"              
[15,] ""    "71" ""   ""    "Max COATES"      "GBR" "Team Hard"                
[16,] ""    "62" "G"  ""    "Jack YOUNG"      "GBR" "M.R.M"                    
      [,8]   [,9]        [,10]    [,11]       [,12]   [,13]        [,14]
 [1,] "LAPS" "TIME"      "GAP"    "DIFF"      "MPH"   "BEST"       "ON" 
 [2,] "19"   "18:53.152" ""       ""          "72.91" "58.808"     "3"  
 [3,] "19"   "18:53.503" "0.351"  "0.351"     "72.89" "58.989"     "3"  
 [4,] "19"   "19:03.496" "10.344" "9.993"     "72.25" "59.573"     "5"  
 [5,] "19"   "19:04.060" "10.908" "0.564"     "72.21" "59.581"     "5"  
 [6,] "19"   "19:04.414" "11.262" "0.354"     "72.19" "59.427"     "7"  
 [7,] "19"   "19:13.863" "20.711" "9.449"     "71.60" "59.588"     "4"  
 [8,] "19"   "19:14.184" "21.032" "0.321"     "71.58" "59.507"     "2"  
 [9,] "19"   "19:14.352" "21.200" "0.168"     "71.57" "59.569"     "4"  
[10,] "19"   "19:15.150" "21.998" "0.798"     "71.52" "59.672"     "3"  
[11,] "19"   "19:34.355" "41.203" "19.205"    "70.35" "1:00.634"   "12" 
[12,] ""     ""          ""       ""          ""      ""           ""   
[13,] "0"    ""          ""       ""          ""      ""           ""   
[14,] ""     ""          ""       ""          ""      ""           ""   
[15,] "3"    "58.808"    ""       "73.94 mph" ""      "119.00 kph" ""   
[16,] "3"    "58.989"    ""       "73.71 mph" ""      "118.63 kph" ""

In [28]:
#Will need tidying
extract_tables("2019/191403cli.pdf", pages = 20:23)

[[1]]
      [,1]                                                                             
 [1,] "SECTOR 1 = FL to I1,SECTOR 2 = I1 to FL,DIFF = Difference To Personal Best Lap,"
 [2,] "P1 71 Max COATES"                                                               
 [3,] "IDEAL LAP TIME :  58.733 BEST LAP TIME :  58.808"                               
 [4,] "LAP SECTOR 1 SECTOR 2"                                                          
 [5,] "1 - 89.0 24.253 106.1"                                                          
 [6,] "2 - 35.155 89.2 23.929 107.5"                                                   
 [7,] "3 - 34.891 89.5 23.917 107.3"                                                   
 [8,] "4 - 34.940 89.0 24.076 107.2"                                                   
 [9,] "5 - 34.979 89.3 24.032 107.0"                                                   
[10,] "6 - 34.977 89.4 24.068 107.0"                                                   
[11,] "7 - 35.100 88.8 24.130 107.3"                                                   
[12,] "8 - 34.816 89.5 24.156 106.8"                                                   
[13,] "9 - 35.051 89.1 24.223 107.2"                                                   
[14,] "10 - 35.101 89.1 24.189 107.0"                                                  
[15,] "11 - 35.243 89.1 24.247 106.6"                                                  
[16,] "12 - 35.168 88.8 24.260 106.6"                                                  
[17,] "13 - 35.231 89.0 24.401 106.3"                                                  
[18,] "14 - 35.211 89.4 24.290 106.5"                                                  
[19,] "15 - 35.249 89.1 24.289 107.2"                                                  
[20,] "16 - 35.237 89.7 24.251 107.2"                                                  
[21,] "17 - 35.233 89.9 24.437 106.5"                                                  
[22,] "18 - 35.303 89.0 24.391 106.6"                                                  
[23,] "19 - 35.280 89.4 24.470 106.6"                                                  
[24,] "P2 62 G Jack YOUNG"                                                             
[25,] "IDEAL LAP TIME :  58.806 BEST LAP TIME :  58.989"                               
[26,] "LAP SECTOR 1 SECTOR 2"                                                          
[27,] "1 - 90.0 23.963 105.3"                                                          
[28,] "2 - 35.750 88.0 23.963 109.1"                                                   
[29,] "3 - 35.003 90.6 23.986 108.4"                                                   
[30,] "4 - 35.211 90.0 24.000 108.0"                                                   
[31,] "5 - 35.000 90.0 24.007 108.4"                                                   
[32,] "6 - 35.183 90.3 24.103 108.5"                                                   
[33,] "7 - 35.155 89.0 24.122 108.0"                                                   
[34,] "8 - 34.843 89.7 24.199 108.2"                                                   
[35,] "9 - 35.339 89.8 24.202 108.2"                                                   
[36,] "10 - 35.108 89.0 24.311 107.7"                                                  
[37,] "11 - 35.056 89.0 24.211 107.2"                                                  
[38,] "12 - 35.092 89.1 24.227 107.5"                                                  
[39,] "13 - 35.133 89.5 24.200 107.3"                                                  
[40,] "14 - 35.355 89.7 24.183 107.7"                                                  
[41,] "15 - 35.393 89.5 24.176 107.8"                                                  
[42,] "16 - 35.359 90.1 24.149 108.2"                                                  
[43,] "17 - 35.025 90.5 24.292 107.7"                                                  
[44,] "18 - 35.141 90.3 24.166 108.2"                                                  
[45,] "19 - 35.279 89.7 24.302 109

In [29]:
extract_tables("2019/191403cli.pdf", pages = 24)

[[1]]
      [,1] [,2] [,3]        [,4]   [,5] [,6]        [,7]   
 [1,] "1"  "62" "YOUNG"     "90.6" "29" "ROBINSON"  "110.7"
 [2,] "2"  "23" "HAMMERTON" "90.4" "9"  "EDWARDS"   "110.3"
 [3,] "3"  "12" "LIDSEY"    "90.1" "21" "DAVIS"     "110.3"
 [4,] "4"  "21" "DAVIS"     "90.0" "23" "HAMMERTON" "110.1"
 [5,] "5"  "71" "COATES"    "89.9" "5"  "COLBURN"   "109.8"
 [6,] "6"  "41" "THOMPSON"  "89.9" "12" "LIDSEY"    "109.6"
 [7,] "7"  "5"  "COLBURN"   "89.9" "41" "THOMPSON"  "109.4"
 [8,] "8"  "29" "ROBINSON"  "89.8" "62" "YOUNG"     "109.1"
 [9,] "9"  "9"  "EDWARDS"   "89.3" "11" "WARR"      "108.0"
[10,] "10" "11" "WARR"      "89.0" "71" "COATES"    "107.5"

In [30]:
extract_tables("2019/191403cli.pdf", pages = 25)

[[1]]
      [,1] [,2] [,3]        [,4]     [,5] [,6]        [,7]     [,8] [,9]
 [1,] ""   ""   ""          ""       ""   ""          ""       ""   ""  
 [2,] "1"  "71" "COATES"    "34.816" "9"  "EDWARDS"   "23.762" "1"  "71"
 [3,] "2"  "62" "YOUNG"     "34.843" "12" "LIDSEY"    "23.797" "2"  "62"
 [4,] "3"  "21" "DAVIS"     "35.235" "29" "ROBINSON"  "23.840" "3"  "9" 
 [5,] "4"  "23" "HAMMERTON" "35.305" "71" "COATES"    "23.917" "4"  "12"
 [6,] "5"  "41" "THOMPSON"  "35.356" "62" "YOUNG"     "23.963" "5"  "23"
 [7,] "6"  "5"  "COLBURN"   "35.418" "5"  "COLBURN"   "23.965" "6"  "41"
 [8,] "7"  "9"  "EDWARDS"   "35.435" "41" "THOMPSON"  "23.994" "7"  "29"
 [9,] "8"  "12" "LIDSEY"    "35.461" "23" "HAMMERTON" "24.027" "8"  "5" 
[10,] "9"  "29" "ROBINSON"  "35.531" "21" "DAVIS"     "24.334" "9"  "21"
[11,] "10" "11" "WARR"      "36.168" "11" "WARR"      "24.466" "10" "11"
      [,10]         [,11]      [,12]      [,13]  
 [1,] "PERFECT LAP" "58.578"   ""         ""     
 [2,] "COATES"      "58.733"   "58.808"   "0.075"
 [3,] "YOUNG"       "58.806"   "58.989"   "0.183"
 [4,] "EDWARDS"     "59.197"   "59.427"   "0.230"
 [5,] "LIDSEY"      "59.258"   "59.573"   "0.315"
 [6,] "HAMMERTON"   "59.332"   "59.581"   "0.249"
 [7,] "THOMPSON"    "59.350"   "59.588"   "0.238"
 [8,] "ROBINSON"    "59.371"   "59.507"   "0.136"
 [9,] "COLBURN"     "59.383"   "59.672"   "0.289"
[10,] "DAVIS"       "59.569"   "59.569"   "0.000"
[11,] "WARR"        "1:00.634" "1:00.634" "0.000"

In [31]:
extract_tables("2019/191403cli.pdf", pages = 26:29)

[[1]]
      [,1]                   [,2]       [,3]                   [,4]      
 [1,] "LAP 1 @ 16:55:53.773" ""         "LAP 2 @ 16:56:52.857" ""        
 [2,] "NO BEHIND"            "LAP TIME" "NO BEHIND"            "LAP TIME"
 [3,] "71"                   "1:05.231" "71"                   "59.084"  
 [4,] "62 0.048"             "1:05.279" "62 0.677"             "59.713"  
 [5,] "12 0.304"             "1:05.535" "12 0.887"             "59.667"  
 [6,] "23 0.911"             "1:06.142" "23 1.494"             "59.667"  
 [7,] "9 1.321"              "1:06.552" "9 1.842"              "59.605"  
 [8,] "5 1.465"              "1:06.696" "5 2.448"              "1:00.067"
 [9,] "41 1.943"             "1:07.174" "41 2.792"             "59.933"  
[10,] "21 2.762"             "1:07.993" "29 3.236"             "59.507"  
[11,] "29 2.813"             "1:08.044" "21 4.628"             "1:00.950"
[12,] "11 3.933"             "1:09.164" "11 5.872"             "1:01.023"
      [,5]                   [,6]       [,7]                   [,8]      
 [1,] "LAP 3 @ 16:57:51.665" ""         "LAP 4 @ 16:58:50.681" ""        
 [2,] "NO BEHIND"            "LAP TIME" "NO BEHIND"            "LAP TIME"
 [3,] "71"                   "58.808"   "71"                   "59.016"  
 [4,] "62 0.858"             "58.989"   "62 1.053"             "59.211"  
 [5,] "12 1.825"             "59.746"   "12 2.426"             "59.617"  
 [6,] "23 2.487"             "59.801"   "23 3.093"             "59.622"  
 [7,] "9 2.839"              "59.805"   "9 3.458"              "59.635"  
 [8,] "5 3.312"              "59.672"   "5 4.102"              "59.806"  
 [9,] "41 3.635"             "59.651"   "41 4.207"             "59.588"  
[10,] "29 4.168"             "59.740"   "29 4.730"             "59.578"  
[11,] "21 5.770"             "59.950"   "21 6.323"             "59.569"  
[12,] "11 8.166"             "1:01.102" "11 10.836"            "1:01.686"
      [,9]                   [,10]     
 [1,] "LAP 5 @ 16:59:49.692" ""        
 [2,] "NO BEHIND"            "LAP TIME"
 [3,] "71"                   "59.011"  
 [4,] "62 1.049"             "59.007"  
 [5,] "12 2.988"             "59.573"  
 [6,] "23 3.663"             "59.581"  
 [7,] "9 4.112"              "59.665"  
 [8,] "41 5.441"             "1:00.245"
 [9,] "29 5.650"             "59.931"  
[10,] "5 6.017"              "1:00.926"
[11,] "21 7.086"             "59.774"  
[12,] "11 13.243"            "1:01.418"

[[2]]
      [,1]                   [,2]       [,3]                   [,4]      
 [1,] "LAP 6 @ 17:00:48.737" ""         "LAP 7 @ 17:01:47.967" ""        
 [2,] "NO BEHIND"            "LAP TIME" "NO BEHIND"            "LAP TIME"
 [3,] "71"                   "59.045"   "71"                   "59.230"  
 [4,] "62 1.290"             "59.286"   "62 1.337"             "59.277"  
 [5,] "12 3.942"             "59.999"   "12 4.525"             "59.813"  
 [6,] "23 4.238"             "59.620"   "23 4.767"             "59.759"  
 [7,] "9 4.754"              "59.687"   "9 4.951"              "59.427"  
 [8,] "41 6.248"             "59.852"   "41 6.976"             "59.958"  
 [9,] "29 6.582"             "59.977"   "29 7.104"             "59.752"  
[10,] "5 7.151"              "1:00.179" "5 7.763"              "59.842"  
[11,] "21 8.122"             "1:00.081" "21 8.685"             "59.793"  
[12,] "11 15.968"            "1:01.770" "11 18.761"            "1:02.023"
      [,5]                   [,6]       [,7]                   [,8]      
 [1,] "LAP 8 @ 17:02:46.939" ""         "LAP 9 @ 17:03:46.213" ""        
 [2,] "NO BEHIND"            "LAP TIME" "NO BEHIND"            "LAP TIME"
 [3,] "71"                   "58.972"   "71"                   "59.274"  
 [4,] "62 1.407"             "59.042"   "62 1.674"             "59.541"  
 [5,] "12 5.302"             "59.749"   "12 5.954"             "59.926"  
 [6,] "23 5.617"             "59.822"   "23 6.146"             "59.803"  
 [7,] "9 5.833"              "59.854"   "9 6.579"              

In [35]:
extract_tables("2019/191403cli.pdf", pages = 32)

[[1]]
     [,1] [,2]         [,3]       [,4]           [,5] [,6]       
[1,] "71" "Max COATES" "1:05.231" "16:55:53.789" "1"  "Team Hard"
[2,] "71" "Max COATES" "59.084"   "16:56:52.873" "2"  "Team Hard"
[3,] "71" "Max COATES" "58.808"   "16:57:51.682" "3"  "Team Hard"

[[2]]
     [,1]     [,2]           [,3]         [,4]    [,5]         [,6]        
[1,] "TYPE"   "TIME OF DAY"  "TYPE"       "COUNT" "TOTAL LAPS" "TOTAL TIME"
[2,] "GREEN"  "16:54:48.541" "Green"      "1"     "18"         "18:51.439" 
[3,] "FINISH" "17:13:39.980" "Red"        "0"     "0"          "0.000"     
[4,] ""       ""             "Safety Car" "0"     "0"          "0.000"     
[5,] ""       ""             "FCY"        "0"     "0"          "0.000"

In [36]:
extract_tables("2019/191403cli.pdf", pages = 33)

[[1]]
     [,1] [,2]         [,3]       [,4]           [,5] [,6]       
[1,] "71" "Max COATES" "1:05.231" "16:55:53.789" "1"  "Team Hard"
[2,] "71" "Max COATES" "59.084"   "16:56:52.873" "2"  "Team Hard"
[3,] "71" "Max COATES" "58.808"   "16:57:51.682" "3"  "Team Hard"

In [37]:
extract_tables("2019/191403cli.pdf", pages = 34)

[[1]]
     [,1] [,2]              [,3]       [,4]           [,5] 
[1,] "NO" "NAME"            "LAP TIME" "TIME OF DAY"  "LAP"
[2,] "62" "Jack YOUNG"      "1:05.279" "16:55:53.821" "1"  
[3,] "62" "Jack YOUNG"      "59.713"   "16:56:53.551" "2"  
[4,] "23" "Ethan HAMMERTON" "59.667"   "16:56:54.366" "2"  
[5,] "29" "Finlay ROBINSON" "59.507"   "16:56:56.110" "2"  
[6,] "62" "Jack YOUNG"      "58.989"   "16:57:52.540" "3"  
     [,6]                   
[1,] "VEHICLE"              
[2,] "M.R.M"                
[3,] "M.R.M"                
[4,] "Team Hard"            
[5,] "Westbourne Motorsport"
[6,] "M.R.M"